# Generated by Django 5.1.2 on 2024-10-18 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('zona', models.CharField(choices=[('ZN', 'Zona Norte'), ('ZS', 'Zona Sul'), ('ZL', 'Zona Leste'), ('ZO', 'Zona Oeste')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Habilitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitacao_documento', models.ImageField(blank=True, null=True, upload_to='images/habilitacao/')),
                ('habilitacao_numero', models.IntegerField()),
                ('habilitacao_validade', models.DateField(blank=True, null=True)),
                ('habilitacao_categoria', models.CharField(choices=[('A', 'A'), ('AB', 'AB'), ('AC', 'AC'), ('AD', 'AD'), ('AE', 'AE'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco_residencial', models.CharField(max_length=500)),
                ('numero', models.CharField(max_length=10)),
                ('cep', models.IntegerField(blank=True, null=True)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TransRN.bairro')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('matricula', models.IntegerField()),
                ('telefone', models.IntegerField()),
                ('data_nascimento', models.DateField()),
                ('data_admissao', models.DateField(blank=True, null=True)),
                ('habilitacao', models.BooleanField(default=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/funcionario/')),
                ('pasep', models.IntegerField(blank=True, null=True)),
                ('observacoes', models.CharField(blank=True, max_length=5000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TransRN.funcionario')),
                ('habilitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TransRN.habilitacao')),
            ],
        ),
    ]
